<a href="https://colab.research.google.com/github/ronan-cunha/machine-learning-course/blob/main/Notebooks/aula_1_big_data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aula 1 - Manipulação de Big Data em CSV**

Conteúdo
1.   Entendendo os Metadados do Arquivo
2.   Importação de dados específicos

## 1. Entendendo os Metadados do Arquivo

In [7]:
import os
import pandas as pd

In [8]:
file_path = "/content/deputies_dataset.csv"

# A. Tamanho do arquivo no disco
file_size_bytes = os.path.getsize(file_path)
file_size_gb = file_size_bytes / (1024 ** 3)

print(f"Tamanho do arquivo: {file_size_gb:.2f} GB")

Tamanho do arquivo: 0.31 GB

In [9]:

# B. Estimativa rápida do número total de linhas (sem carregar o arquivo na RAM)
# Lendo o arquivo linha por linha via buffer de texto
with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
    total_lines = sum(1 for line in f)

print(f"Total estimado de linhas: {total_lines:,}")

Total estimado de linhas: 3,014,904

In [10]:
# Lendo apenas a linha 0 (cabeçalho) ajustando nrows=0
df_header = pd.read_csv(file_path, nrows=0)
colunas = df_header.columns.tolist()

print(f"Total de colunas: {len(colunas)}")
print("Nomes das colunas:")
for i, col in enumerate(colunas):
    print(f" [{i}] {col}")

Total de colunas: 10
Nomes das colunas:
 [0] bugged_date
 [1] receipt_date
 [2] deputy_id
 [3] political_party
 [4] state_code
 [5] deputy_name
 [6] receipt_social_security_number
 [7] receipt_description
 [8] establishment_name
 [9] receipt_value

In [11]:
# Carrega as 100 primeiras linhas com todas as colunas
df_sample = pd.read_csv(file_path, nrows=100)

print(f"Formato da amostra: {df_sample.shape}")
print("\nVisualização das primeiras 5 linhas:")
display(df_sample.head(10))

Formato da amostra: (100, 10)

Visualização das primeiras 5 linhas:

,bugged_date,receipt_date,deputy_id,political_party,state_code,deputy_name,receipt_social_security_number,receipt_description,establishment_name,receipt_value
0,0,2013-03-27 00:00:00,1772,PSB,SP,Abelardo Camarinha,3.530749e+12,Fuels and lubricants.,AUTO POSTO 314 NORTE LTDA,70
1,0,2013-07-24 00:00:00,1772,PSB,SP,Abelardo Camarinha,8.202116e+12,Fuels and lubricants.,AUTO POSTO AEROPORTO LTDA,104
2,0,2013-02-17 00:00:00,1772,PSB,SP,Abelardo Camarinha,8.202116e+12,Fuels and lubricants.,AUTO POSTO AEROPORTO LTDA,100
3,0,2013-03-15 00:00:00,1772,PSB,SP,Abelardo Camarinha,8.202116e+12,Fuels and lubricants.,AUTO POSTO AEROPORTO LTDA,100
4,0,2013-01-27 00:00:00,1772,PSB,SP,Abelardo Camarinha,8.202116e+12,Fuels and lubricants.,AUTO POSTO AEROPORTO LTDA,77
5,0,2013-02-06 00:00:00,1772,PSB,SP,Abelardo Camarinha,8.202116e+12,Fuels and lubricants.,AUTO POSTO AEROPORTO LTDA,131
6,0,2013-04-18 00:00:00,1772,PSB,SP,Abelardo Camarinha,6.143204e+12,Fuels and lubricants.,AUTO POSTO AV ESMERALDA LTDA,2840
7,0,2013-05-14 00:00:00,1772,PSB,SP,Abelardo Camarinha,6.143204e+12,Fuels and lubricants.,AUTO POSTO AV ESMERALDA LTDA,2517
8,0,2013-06-21 00:00:00,1772,PSB,SP,Abelardo Camarinha,6.143204e+12,Fuels and lubricants.,AUTO POSTO AV ESMERALDA LTDA,2509
9,0,2013-07-20 00:00:00,1772,PSB,SP,Abelardo Camarinha,6.143204e+12,Fuels and lubricants.,AUTO POSTO AV ESMERALDA LTDA,2720

In [12]:
print("\nTipos de dados:")
print(df_sample.dtypes)

Tipos de dados:
bugged_date                         int64
receipt_date                       object
deputy_id                           int64
political_party                    object
state_code                         object
deputy_name                        object
receipt_social_security_number    float64
receipt_description                object
establishment_name                 object
receipt_value                       int64
dtype: object

In [21]:
# Suponha que desejamos analisar apenas a coluna "deputy_id"
coluna_alvo = ["deputy_name"]

df_coluna = pd.read_csv(file_path, usecols=coluna_alvo)

print("Estrutura da coluna importada:")
print(df_coluna.info())
print("\nPrimeiros valores:")
print(df_coluna.head())

Estrutura da coluna importada:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3014902 entries, 0 to 3014901
Data columns (total 1 columns):
 #   Column       Dtype
---  ------       -----
 0   deputy_name  object
dtypes: object(1)
memory usage: 23.0+ MB
None

Primeiros valores:
          deputy_name
0  Abelardo Camarinha
1  Abelardo Camarinha
2  Abelardo Camarinha
3  Abelardo Camarinha
4  Abelardo Camarinha

In [16]:
id = df_coluna['deputy_id'].unique()
len(id)
id

array([1772,  879, 2419, ..., 1920, 1170, 1955])

In [17]:
df_coluna['deputy_id'].nunique()

1188

In [22]:
df_coluna['deputy_name'].value_counts(normalize=False, dropna=False)

deputy_name
Vanderlei Macris       15987
Jorge Tadeu Mudalen    15590
Henrique Fontana       13707
Celso Maldaner         11973
Eduardo Barbosa        11480
                       ...
Juvenil                    1
Jusmari Oliveira           1
Adão Pretto                1
Reinaldo Nogueira          1
Sebastião Madeira          1
Name: count, Length: 1187, dtype: int64

# Perguntas 1
1. Quantos partidos políticos tem na base?
2. Qual o período da base de dados?
3. Quem é o cadidato com mais reembolsos por ano?
4. Quem é o partido com mais reembolsos por ano?

In [31]:
# 1. Quantos partidos políticos tem na base?
coluna_alvo = ["political_party"]
df_coluna = pd.read_csv(file_path, usecols=coluna_alvo)
df_coluna[coluna_alvo].nunique()

political_party    32
dtype: int64

In [32]:
# 2. Qual o período da base de dados?
coluna_alvo = ["receipt_date"]
df_coluna = pd.read_csv(file_path, usecols=coluna_alvo)
df_coluna['receipt_date'] = pd.to_datetime(df_coluna['receipt_date'], format='mixed')
print(f"primeira data:{df_coluna['receipt_date'].min()}")
print(f"última data:{df_coluna['receipt_date'].max()}")

primeira data:2009-01-01 00:00:00
última data:2017-10-24 17:56:47

In [39]:
coluna_alvo = ["receipt_date"]
df_coluna = pd.read_csv(file_path, usecols=coluna_alvo)
df_coluna['receipt_date'] = pd.to_datetime(df_coluna['receipt_date'], format='mixed')
df_coluna.sort_values(by='receipt_date', ascending=False)

               receipt_date
1820575 2017-10-24 17:56:47
2040814 2017-10-24 17:54:44
1825225 2017-10-24 17:48:13
1943281 2017-10-24 17:21:03
1947593 2017-10-24 17:20:21
...                     ...
2911715 2009-01-01 00:00:00
2880106 2009-01-01 00:00:00
2856865 2009-01-01 00:00:00
2856914 2009-01-01 00:00:00
2891467 2009-01-01 00:00:00

[3014902 rows x 1 columns]

In [51]:
coluna_alvo = ["receipt_date", "deputy_name"]
df_coluna = pd.read_csv(file_path, usecols=coluna_alvo)
df_coluna['receipt_date'] = pd.to_datetime(df_coluna['receipt_date'], format='mixed')
df_coluna['ano'] = df_coluna['receipt_date'].dt.year
result = df_coluna[['ano','deputy_name']].value_counts(normalize=False, dropna=False)
type(result)
result = pd.DataFrame(result)
result.columns
result.groupby('ano')['count'].max()

ano
2009    1795
2010    2633
2011    2611
2012    2112
2013    2281
2014    1922
2015    2084
2016    2308
2017    1647
Name: count, dtype: int64

# Perguntas 2:
1. Qual o tipo de base de dados temos?
2. Como podemos identificar uma unidade dessa base de dados?
3. Há unidades repetidas?